<div class="container loginView">
	<div class="row">
		<div class="col-md-12 col-lg-10 mx-auto">
			<img id="photoLogIn"src="<?= $wwwUrl ?>/images/smoothiepack.png" alt="photoLogIn">
		</div>
	</div>
	<div class="row">
		<div class = "col-12 seConnecter">
			<h2 class="title Abhaya"><i class="fa fa-lock"></i> SE CONNECTER </h2>
		</div>
	<div>
	<div class="row">
		<div class="col-12 text-center">
		<p>En vous connectant, vous pouvez commander des smoothies, ajouter nos recettes "maison" à votre liste de recettes favorites, accéder à votre panier, et bien plus encore...!!
		<p>Vous n'avez pas encore d'espace membre ? cliquez vite sur "créer un compte" pour nous rejoindre. Sinon, merci de vous identifier
		</div>
	</div>
	<div class="row">
		<div class="col-4 buttonCreer"  >
			<li>
				<a class="button button-primary" id="buttonCreer" href="<?= $requestUrl ?>/user">CREER UN COMPTE</a>
			</li>
		</div>
	</div>
	<div class="row">
		<div class="col-md-10 col-sm-12 col-xs-12 authentification">
			<form class="generic-form" action="<?= $requestUrl ?>/user/login" method="POST">

				<aside class="error-message hidden">
					<h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
					<p><?= $errorMessage ?></p>
				</aside>

				<fieldset class="userInfos">

				<div class="shadow p-3 mb-5 bg-white rounded col-8 mx-auto ">
					
					<ul>
						<li>
							<label for="email">E-mail :</label>
							<input id="email" type="text" name="email" data-required data-name="E-mail" value="<?= $email ?>">
						</li>
						<li>
							<label for="password">Mot de passe :</label>
							<input id="password" type="password" name="password" data-required data-name="Mot de passe">
						</li>
					</ul>
				</div>

				</fieldset>
				<ul class="col-4">
					<li>
						<input class="button " id="buttonConnexion" type="submit" value="CONNEXION">
					</li>
				</ul>

			</form>
		</div>
	</div>

</div>

<script type="text/javascript" src="<?= $wwwUrl ?>/js/layout.js"></script>


