<h2><i class="fa fa-star"></i> Commande payée</h2>

<h3>Merci d'avoir commandé chez Smoothie Maker !</h3>

<p data-order-step="success">Votre commande a bien été enregistrée. Venez la récupérer chez nous, nous vous attendons.</p>
<p class="layout-center"><img alt="Commande payée" src="<?= $wwwUrl ?>/images/hotel-ermitage-terrasse.jpg"></p>

<a class="button button-primary" href="<?= $requestUrl ?>">Accueil</a>


<!-- Classes de gestion du formulaire de commande -->
<!-- Ce code JavaScript n'est chargé QUE depuis l'URL /order/payment/success -->
<script src="<?= $wwwUrl ?>/js/classes/BasketSession.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
<script type="text/javascript" src="<?= $wwwUrl ?>/js/layout.js"></script>