
<h2 class="title Abhaya"><i class="fa fa-shopping-cart"></i> Passer une commande</h2>

<form data-order-step="run" id="order-form" class="generic-form hidden">

    <!-- Champ caché stockant le prix de vente du produit alimentaire sélectionné -->
    <input type="hidden" name="salePrice">

    <aside class="error-message hidden">
        <h3><i class="fa fa-warning"></i> Il y a <em class="total-error-count">1</em> erreur(s) dans le formulaire !</h3>
        <p></p>
    </aside>

    <fieldset id="taille-image">
        <legend><strong>Ajouter un article</strong></legend>
        <ul>
            <li>
            
                <div>Choisissez votre smoothie : 
                <select id="meal" name="meal">
                    <?php foreach($meals as $meal): ?>
                        <option value="<?= $meal['Id']; ?>"><?= $meal['Name']; ?></option>
                    <?php endforeach; ?>
                </select>
                </div>

                
                    <article id="meal-details" class="meal-details no-left-label">
                        <img id="imgOrder" src="<?= $wwwUrl ?>/images/<?= $meal['Photo']; ?>" alt="Photo du produit">
                        <p></p>
                        <span>Prix : <strong><?= number_format($meal['SalePrice'], 2) ?> €</strong></span>
                    </article>
                  
            </li>
            <li>
                <label for="quantity">Quantité :</label>
                <input id="quantity" class="quantity" type="text" maxlength="2" name="quantity" data-name="Quantité" data-type="positive-integer" data-required><strong id='alert'></strong>
            </li>
            <li>
                <button class="button button-primary" type="submit">Ajouter</button>
            </li>
        </ul>
    </fieldset>

    <fieldset>
        <legend>Récapitulatif de la commande</legend>
        <section id="order-summary"></section>
    </fieldset>
</form>

<ul class="link-list text-center ulOrder">
    <li>
        <button id="validate-order" class="button button-primary" disabled>Valider la commande</button>
        <a class="button button-cancel small" href="<?= $requestUrl ?>">Annuler</a>
    </li> 
</ul>


<!-- Classes de gestion du formulaire de commande -->
<!-- Ce code JavaScript n'est chargé QUE depuis l'URL /order/payment/success -->
<script src="<?= $wwwUrl ?>/js/layout.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/BasketSession.class.js"></script>
<script src="<?= $wwwUrl ?>/js/classes/OrderForm.class.js"></script>
