
<h2 class="title Abhaya "><i class="fa fa-cogs"></i> PANNEAU D'ADMINISTRATION</h2>

<form class="generic-form mx-auto" action="<?= $requestUrl ?>/admin/user" method="POST">

	<fieldset>
		<legend class="mx-auto"><i class="fa fa-lock"></i> Historique des commandes</legend>
		<ul>
	        <li>
	        	<table id="table-order" class="mx-auto">
	        	<thead>
	        		<tr>
	        			<th>Num Com</th>
	        			<th>Num User</th>
	        			<th>Date Créa</th>
	        			<th>Date Succ</th>
	        			<th>tva</th>
	        			<th>total</th>
	        		</tr>
	        	</thead>
	        	<tbody>
				<?php foreach ($orders as $order): ?>
					<tr>
						<td>							
							<a name="<?= $order['Id'] ?>"><?= $order['Id'] ?></a>
						</td>
						<td>
							<a name="<?= $order['User_Id'] ?>"><?= $order['User_Id'] ?></a>
						</td>
						<td>
							<?= $order['CreationTimestamp'] ?>
						</td>
						<td>
							<?= $order['TaxRate'] ?> %
						</td>
						<td>
							<?= $order['TaxAmount'] ?> €
						</td>
						<td>
							<?= $order['TotalAmount'] ?> €
						</td>
					</tr>
					<?php endforeach; ?>
	        </li>
	        	</tbody>
	        	</table>
		</ul>
	</fieldset>

</form>


<script type="text/javascript" src="<?= $wwwUrl ?>/js/layout.js"></script>

