<div class="container-fluid ">
	
	<div class="row ">
		<div class="col-lg-5 col-md-12 col-sm-12  col-xs-12">
			<img src="<?= $wwwUrl ?>/images/hotel-ermitage-terrasse.jpg" class="imgAccueil">			
		</div>
		
			<div class="jumbotron col-lg-7 col-md-12 col-sm-12 col-xs-12 text-center bg-transparent" id="notreBar">
				  <div class="title Abhaya">NOTRE BAR A SMOOTHIE</div>
				  <p class="lead">Venez profiter de la terasse ombragée. Nos smoothies peuvent être servis accompagné de petite douceurs gourmandes. Nos smoothies sont bio et fait avec des produits de saison.</p>
			</div>			
		
	</div>

	<div class="row">
		<div class="col-lg-5 col-sm-12 col-md-12 col-xs-12">
			<div class="jumbotron text-center bg-transparent">
				  <div class="title Abhaya">Nous trouver</div>
				  <p class="lead">Venez vous détendre dans notre salon smooth.</p>
			</div>
		</div>
	</div>
	<div class="row">

		<div class="col-lg-5 col-sm-12 col-md-12 col-xs-12">
			<div class="jumbotron text-center bg-transparent">

				<div class="shadow p-3 mb-5 bg-white rounded pinkgrad">
					<i class="far fa-clock">Accès</i>
					<p>Adresse :<br>52 rue de rivoli</p>
					<p>Métro :<br>Hôtel de Ville (lignes 1 et 11)</p>
					<p>Parking LOBAU :<br> 700 places,<br>4 rue Lobau</p>
					<p>Parking BAUDOYER:<br> 200 places, 6 place Baudoyer</p>
					
				</div>


				<div class="title Abhaya">Nos horaires</div>

				<div class="shadow p-3 mb-5 bg-white rounded pinkgrad">
					<i class="far fa-clock"></i>
					<p>Du Lundi au Vendredi :<br> 11H30 - 22H</p>
					<p>Le samedi :<br> 11H00 - Minuit<p>
					<p>Le Dimanche :<br> 11H-15H<p>
				</div>
			</div>
		</div>

		<div class="col-lg-7 col-sm-12 col-md-12 col-xs-12">
			
			<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2783.6910720371243!2d4.897539351371386!3d45.75733892175331!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x47f4c1b3f05b23bb%3A0x758727ce4edd027c!2s3w+Academy!5e0!3m2!1sen!2sfr!4v1557483192071!5m2!1sen!2sfr" width="100%" height="700" frameborder="0" style="border:0" allowfullscreen></iframe>
			
		</div>
		
	</div>

	<div class="row ">

	<div class="col-lg-6 col-sm-12 col-md-10 col-xs-12 text-center mx-auto">

		<div class="shadow p-3 mb-5 rounded">

			 <div class="title Abhaya">Nous contacter</div>

			<input type="email" name="email" id="mail" placeholder="Adresse email">

			<input type="text" name="msg" id="msg" placeholder="Message">
			
		</div>

		 	 <button type="button" class="btn pinkBtn"><a href="<?= $requestUrl ?>/user/login">ENVOYER</a></button>
	</div>
		
	</div>


</div>

<script type="text/javascript" src="<?= $wwwUrl ?>/js/layout.js"></script>